export const selectBrand = state => state.filters.brand;
export const selectColor = state => state.filters.color;
export const selectHookahSize = state => state.filters.hookah_size;
export const selectPrice = state => state.filters.price;
export const selectSize = state => state.filters.size;
export const selectStatus = state => state.filters.status;
export const selectType = state => state.filters.type;
export const selectWeight = state => state.filters.weight;
export const selectFlavor = state => state.filters.flavor;
