export const items = [
  {
    id: 1,
    promotion: 'Hot',
    price: 900,
    subTitle: 'Brand',
    title: 'Shisha huisha fdsfsf sdf sfdefsesff efsefs',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
  },
  {
    id: 2,
    promotion: 'New',
    price: 300,
    subTitle: 'Brand',
    title: 'Smoke machine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
  },
  {
    id: 3,
    promotion: 'Sale',
    price: 200,
    subTitle: 'Brand',
    title: 'Big tower shisha',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
  },
  {
    id: 4,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
  },
  {
    id: 5,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
  },
  {
    id: 6,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
  },
  {
    id: 7,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
  },
  {
    id: 8,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
  },
  {
    id: 9,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
  },
  {
    id: 10,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
  },
];

export const images = [
  { uri: '/hookah1.jpg' },
  { uri: '/hookah2.jpg' },
  { uri: '/hookah3.jpg' },
  { uri: '/hookah4.jpg' },
  { uri: '/hookah5.jpg' },
];

export const categories = [
  {
    id: 1,
    image: '/hookah_cat.jpg',
    title: 'Hookah',
    description: 'Best hookah in the World',
  },
  {
    id: 2,
    image: '/tobako_cat.jpg',
    title: 'Tobako',
    description: 'Best tobako in the World',
  },
  {
    id: 3,
    image: '/coal_cat.jpg',
    title: 'Coal',
    description: 'Best coal in the World',
  },
  {
    id: 4,
    image: '/bowl_cat.jpg',
    title: 'Hookah bowl',
    description: 'Best hookah bowl in the World',
  },
];
