export const items = [
  {
    id: 1,
    promotion: 'Hot',
    price: 900,
    subTitle: 'Brand',
    title: 'Shisha huisha fdsfsf sdf sfdefsesff efsefs',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 2,
    promotion: 'New',
    price: 300,
    subTitle: 'Brand',
    title: 'Smoke machine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 3,
    promotion: 'Sale',
    price: 200,
    subTitle: 'Brand',
    title: 'Big tower shisha',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 4,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 5,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 6,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 7,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 8,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 9,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 10,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 11,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 12,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: true,
  },
  {
    id: 13,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 14,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 15,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 16,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 17,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 18,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 19,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 20,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 21,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 22,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 23,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 24,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 25,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 26,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 27,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 28,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 29,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
  {
    id: 30,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'High quality, produced in Ukraine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
    isPromoted: false,
  },
];

export const images = [
  { uri: '/hookah1.jpg' },
  { uri: '/hookah2.jpg' },
  { uri: '/hookah3.jpg' },
  { uri: '/hookah4.jpg' },
  { uri: '/hookah5.jpg' },
];

export const categories = [
  {
    id: 1,
    image: '/hookah_cat.jpg',
    name: 'Hookahs',
    description: 'Best hookah in the World',
    uri: '/',
    subCategory: [
      { id: 1, name: 'Brand 1', uri: '/', logo: '/brand.jpg' },
      { id: 2, name: 'Brand 2', uri: '/', logo: '/brand.jpg' },
      { id: 3, name: 'Brand 3', uri: '/', logo: '/brand.jpg' },
      { id: 4, name: 'Brand 4', uri: '/', logo: '/brand.jpg' },
      { id: 5, name: 'Brand 5', uri: '/', logo: '/brand.jpg' },
      { id: 6, name: 'Brand 6', uri: '/', logo: '/brand.jpg' },
      { id: 7, name: 'Brand 7', uri: '/', logo: '/brand.jpg' },
      { id: 8, name: 'Brand 8', uri: '/', logo: '/brand.jpg' },
      { id: 9, name: 'Brand 9', uri: '/', logo: '/brand.jpg' },
      { id: 10, name: 'Brand 10', uri: '/', logo: '/brand.jpg' },
    ],
  },
  {
    id: 2,
    image: '/tobako_cat.jpg',
    name: 'Tobacco',
    description: 'Best tobacco in the World',
    uri: '/',
    subCategory: [
      { id: 1, name: 'Brand 1', uri: '/', logo: '/brand.jpg' },
      { id: 2, name: 'Brand 2', uri: '/', logo: '/brand.jpg' },
      { id: 3, name: 'Brand 3', uri: '/', logo: '/brand.jpg' },
      { id: 4, name: 'Brand 4', uri: '/', logo: '/brand.jpg' },
      { id: 5, name: 'Brand 5', uri: '/', logo: '/brand.jpg' },
      { id: 6, name: 'Brand 6', uri: '/', logo: '/brand.jpg' },
      { id: 7, name: 'Brand 7', uri: '/', logo: '/brand.jpg' },
      { id: 8, name: 'Brand 8', uri: '/', logo: '/brand.jpg' },
      { id: 9, name: 'Brand 9', uri: '/', logo: '/brand.jpg' },
      { id: 10, name: 'Brand 10', uri: '/', logo: '/brand.jpg' },
      { id: 11, name: 'Brand 11', uri: '/', logo: '/brand.jpg' },
      { id: 12, name: 'Brand 12', uri: '/', logo: '/brand.jpg' },
      { id: 13, name: 'Brand 13', uri: '/', logo: '/brand.jpg' },
      { id: 14, name: 'Brand 14', uri: '/', logo: '/brand.jpg' },
      { id: 15, name: 'Brand 15', uri: '/', logo: '/brand.jpg' },
    ],
  },
  {
    id: 3,
    image: '/coal_cat.jpg',
    name: 'Coals',
    description: 'Best coal in the World',
    uri: '/',
    subCategory: [
      { id: 1, name: 'Brand 1', uri: '/', logo: '/brand.jpg' },
      { id: 2, name: 'Brand 2', uri: '/', logo: '/brand.jpg' },
      { id: 3, name: 'Brand 3', uri: '/', logo: '/brand.jpg' },
      { id: 4, name: 'Brand 4', uri: '/', logo: '/brand.jpg' },
      { id: 5, name: 'Brand 5', uri: '/', logo: '/brand.jpg' },
      { id: 6, name: 'Brand 6', uri: '/', logo: '/brand.jpg' },
      { id: 7, name: 'Brand 7', uri: '/', logo: '/brand.jpg' },
      { id: 8, name: 'Brand 8', uri: '/', logo: '/brand.jpg' },
      { id: 9, name: 'Brand 9', uri: '/', logo: '/brand.jpg' },
      { id: 10, name: 'Brand 10', uri: '/', logo: '/brand.jpg' },
    ],
  },
  {
    id: 4,
    image: '/bowl_cat.jpg',
    name: 'Bowls',
    description: 'Best hookah bowl in the World',
    uri: '/',
    subCategory: [
      { id: 1, name: 'Brand 1', uri: '/', logo: '/brand.jpg' },
      { id: 2, name: 'Brand 2', uri: '/', logo: '/brand.jpg' },
      { id: 3, name: 'Brand 3', uri: '/', logo: '/brand.jpg' },
      { id: 4, name: 'Brand 4', uri: '/', logo: '/brand.jpg' },
      { id: 5, name: 'Brand 5', uri: '/', logo: '/brand.jpg' },
      { id: 6, name: 'Brand 6', uri: '/', logo: '/brand.jpg' },
      { id: 7, name: 'Brand 7', uri: '/', logo: '/brand.jpg' },
      { id: 8, name: 'Brand 8', uri: '/', logo: '/brand.jpg' },
      { id: 9, name: 'Brand 9', uri: '/', logo: '/brand.jpg' },
      { id: 10, name: 'Brand 10', uri: '/', logo: '/brand.jpg' },
    ],
  },
];

export const brands = [
  { id: 1, name: 'Armani ' },
  { id: 2, name: 'Apple' },
  { id: 3, name: 'Alpha Industries' },
  { id: 4, name: 'Batman' },
  { id: 5, name: 'Berwin and Berwin' },
  { id: 6, name: 'Chatham' },
  { id: 7, name: 'Chi Chi' },
  { id: 8, name: 'Digby and Fox' },
  { id: 9, name: 'Disney' },
  { id: 10, name: 'DJI' },
];

export const weight = [
  { id: 1, name: 25 },
  { id: 2, name: 50 },
  { id: 3, name: 100 },
  { id: 4, name: 125 },
  { id: 5, name: 150 },
  { id: 6, name: 250 },
  { id: 7, name: 500 },
  { id: 8, name: 1000 },
];

export const colors = [
  { id: 1, name: 'White' },
  { id: 2, name: 'Gold' },
  { id: 3, name: 'Black' },
  { id: 4, name: 'Red' },
  { id: 5, name: 'Purple' },
  { id: 6, name: 'Blue' },
  { id: 7, name: 'Green' },
  { id: 8, name: 'Yellow' },
];

export const status = [
  { id: 1, name: 'In stock' },
  { id: 2, name: 'Out of stock' },
  { id: 3, name: 'Ending' },
  { id: 4, name: 'Awaiting' },
];
