export const items = [
  {
    id: 1,
    promotion: 'Hot',
    price: 900,
    subTitle: 'Brand',
    title: 'Shisha huisha fdsfsf sdf sfdefsesff efsefs',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
  },
  {
    id: 2,
    promotion: 'New',
    price: 300,
    subTitle: 'Brand',
    title: 'Smoke machine',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
  },
  {
    id: 3,
    promotion: 'Sale',
    price: 200,
    subTitle: 'Brand',
    title: 'Big tower shisha',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
  },
  {
    id: 4,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
  },
  {
    id: 5,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
  },
  {
    id: 6,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
  },
  {
    id: 7,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
  },
  {
    id: 8,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
  },
  {
    id: 9,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
  },
  {
    id: 10,
    promotion: '',
    price: 450,
    subTitle: 'Brand',
    title: 'Hookah huiukah',
    images: ['/hookah_item.jpg', '/hookah_item2.jpg'],
    available: 12,
  },
];

export const images = [
  { uri: '/hookah1.jpg' },
  { uri: '/hookah2.jpg' },
  { uri: '/hookah3.jpg' },
  { uri: '/hookah4.jpg' },
  { uri: '/hookah5.jpg' },
];

export const categories = [
  {
    id: 1,
    image: '/hookah_cat.jpg',
    name: 'Hookahs',
    description: 'Best hookah in the World',
    uri: '/',
    subCategory: [
      { id: 1, name: 'Brand 1', uri: '/', logo: '/brand.jpg' },
      { id: 2, name: 'Brand 2', uri: '/', logo: '/brand.jpg' },
      { id: 3, name: 'Brand 3', uri: '/', logo: '/brand.jpg' },
      { id: 4, name: 'Brand 4', uri: '/', logo: '/brand.jpg' },
      { id: 5, name: 'Brand 5', uri: '/', logo: '/brand.jpg' },
      { id: 6, name: 'Brand 6', uri: '/', logo: '/brand.jpg' },
      { id: 7, name: 'Brand 7', uri: '/', logo: '/brand.jpg' },
      { id: 8, name: 'Brand 8', uri: '/', logo: '/brand.jpg' },
      { id: 9, name: 'Brand 9', uri: '/', logo: '/brand.jpg' },
      { id: 10, name: 'Brand 10', uri: '/', logo: '/brand.jpg' },
    ],
  },
  {
    id: 2,
    image: '/tobako_cat.jpg',
    name: 'Tobacco',
    description: 'Best tobacco in the World',
    uri: '/',
    subCategory: [
      { id: 1, name: 'Brand 1', uri: '/', logo: '/brand.jpg' },
      { id: 2, name: 'Brand 2', uri: '/', logo: '/brand.jpg' },
      { id: 3, name: 'Brand 3', uri: '/', logo: '/brand.jpg' },
      { id: 4, name: 'Brand 4', uri: '/', logo: '/brand.jpg' },
      { id: 5, name: 'Brand 5', uri: '/', logo: '/brand.jpg' },
      { id: 6, name: 'Brand 6', uri: '/', logo: '/brand.jpg' },
      { id: 7, name: 'Brand 7', uri: '/', logo: '/brand.jpg' },
      { id: 8, name: 'Brand 8', uri: '/', logo: '/brand.jpg' },
      { id: 9, name: 'Brand 9', uri: '/', logo: '/brand.jpg' },
      { id: 10, name: 'Brand 10', uri: '/', logo: '/brand.jpg' },
      { id: 11, name: 'Brand 11', uri: '/', logo: '/brand.jpg' },
      { id: 12, name: 'Brand 12', uri: '/', logo: '/brand.jpg' },
      { id: 13, name: 'Brand 13', uri: '/', logo: '/brand.jpg' },
      { id: 14, name: 'Brand 14', uri: '/', logo: '/brand.jpg' },
      { id: 15, name: 'Brand 15', uri: '/', logo: '/brand.jpg' },
    ],
  },
  {
    id: 3,
    image: '/coal_cat.jpg',
    name: 'Coals',
    description: 'Best coal in the World',
    uri: '/',
    subCategory: [
      { id: 1, name: 'Brand 1', uri: '/', logo: '/brand.jpg' },
      { id: 2, name: 'Brand 2', uri: '/', logo: '/brand.jpg' },
      { id: 3, name: 'Brand 3', uri: '/', logo: '/brand.jpg' },
      { id: 4, name: 'Brand 4', uri: '/', logo: '/brand.jpg' },
      { id: 5, name: 'Brand 5', uri: '/', logo: '/brand.jpg' },
      { id: 6, name: 'Brand 6', uri: '/', logo: '/brand.jpg' },
      { id: 7, name: 'Brand 7', uri: '/', logo: '/brand.jpg' },
      { id: 8, name: 'Brand 8', uri: '/', logo: '/brand.jpg' },
      { id: 9, name: 'Brand 9', uri: '/', logo: '/brand.jpg' },
      { id: 10, name: 'Brand 10', uri: '/', logo: '/brand.jpg' },
    ],
  },
  {
    id: 4,
    image: '/bowl_cat.jpg',
    name: 'Bowls',
    description: 'Best hookah bowl in the World',
    uri: '/',
    subCategory: [
      { id: 1, name: 'Brand 1', uri: '/', logo: '/brand.jpg' },
      { id: 2, name: 'Brand 2', uri: '/', logo: '/brand.jpg' },
      { id: 3, name: 'Brand 3', uri: '/', logo: '/brand.jpg' },
      { id: 4, name: 'Brand 4', uri: '/', logo: '/brand.jpg' },
      { id: 5, name: 'Brand 5', uri: '/', logo: '/brand.jpg' },
      { id: 6, name: 'Brand 6', uri: '/', logo: '/brand.jpg' },
      { id: 7, name: 'Brand 7', uri: '/', logo: '/brand.jpg' },
      { id: 8, name: 'Brand 8', uri: '/', logo: '/brand.jpg' },
      { id: 9, name: 'Brand 9', uri: '/', logo: '/brand.jpg' },
      { id: 10, name: 'Brand 10', uri: '/', logo: '/brand.jpg' },
    ],
  },
];

export const brands = [
  { id: 1, name: 'Abc' },
  { id: 2, name: 'Btc' },
  { id: 3, name: 'Cdo' },
  { id: 4, name: 'Arb' },
  { id: 5, name: 'Etf' },
  { id: 6, name: 'Bob' },
  { id: 7, name: 'Gld' },
  { id: 8, name: 'Int' },
  { id: 9, name: 'Klm' },
  { id: 10, name: 'Nft' },
];

export const weight = [
  { id: 1, gram: 25 },
  { id: 2, gram: 50 },
  { id: 3, gram: 100 },
  { id: 4, gram: 125 },
  { id: 5, gram: 150 },
  { id: 6, gram: 250 },
  { id: 7, gram: 500 },
  { id: 8, gram: 1000 },
];

export const colors = [
  { id: 1, name: 'white' },
  { id: 2, name: 'gold' },
  { id: 3, name: 'black' },
  { id: 4, name: 'red' },
  { id: 5, name: 'purple' },
  { id: 6, name: 'blue' },
  { id: 7, name: 'green' },
  { id: 8, name: 'yelow' },
];
